reduction: sum
criterions:
  -
    name: heatmap_loss
    target_key: TARGET_LANDMARKS_HEATMAP
    output_key: OUTPUT_LANDMARKS_HEATMAP
    weight: 1.
    loss:
      _target_: model_training.losses.IoULoss

  -
    name: vertices3d_loss
    target_key: TARGET_3D_MODEL_VERTICES
    output_key: OUTPUT_3DMM_PARAMS
    weight: 50.
    loss:
      _target_: model_training.losses.Vertices3DLoss
      criterion: l2 # choose from {l1, l2, smooth_l1}
      batch_size: ${batch_size}
      consts: ${constants}
      weights_and_indices:
        flame_indices: ${train.flame_indices}
        weights: {'head': .5, 'face_w_ears': .75, 'face': 1.}


  - name: reprojection_loss
    target_key: TARGET_2D_FULL_LANDMARKS
    output_key: OUTPUT_3DMM_PARAMS
    weight: 0.05
    loss:
      _target_: model_training.losses.ReprojectionLoss
      criterion: smooth_l1
      batch_size: ${batch_size}
      consts: ${constants}
      img_size: ${train.img_size}
      weights_and_indices:
        flame_indices: ${train.flame_indices}
        weights: {'face': .5, 'face_w_ears': .5}

  - name: landmarks_loss
    target_key:
      - TARGET_2D_LANDMARKS
      - TARGET_2D_LANDMARKS_PRESENCE
    output_key:
      - OUTPUT_2D_LANDMARKS
      - TARGET_2D_LANDMARKS_PRESENCE
    weight: 100.
    loss:
      _target_: model_training.losses.LandmarksLossWVisibility
      criterion: smooth_l1
